### ISSUE TITLE
Getting Exception while trying trying this module from deno CLI 

### ISSUE THREAD

**Issue by rahuledjx** [zhmushan/dev_server#1]
`Command ` deno run -A --unstable https://deno.land/x/dev_server/mod.ts --template hello_world

`Error` 
> Compile` https://deno.land/std@v0.50.0/fs/mod.ts
error: TS2322 [ERROR]: Type 'string' is not assignable to type 'boolean'.
  return srcArray.reduce(
  at https://deno.land/std@v0.50.0/fs/_util.ts:20:3

`Deno Version` 1.0.0

**Comment by zhmushan** [comment]
Thanks for pointing out, I haven't tested it in deno@1.0.0, I will do it later.

**Comment by zhmushan** [comment]
https://github.com/zhmushan/dev_server/commit/6a4a4afff52eb1f9195588eb95ae3b52c801bcc5
