### ISSUE TITLE
Error when installing

### ISSUE THREAD

**Issue by Hypercubed** [zhmushan/dev_server#5]
Trying to install getting the following error:

```
> deno install -A --unstable https://deno.land/x/dev_server/mod.ts
Check https://deno.land/x/dev_server/mod.ts
error: TS2322 [ERROR]: Type '"esm"' is not assignable to type '"module" | "classic" | undefined'.
      bundle: "esm",
      ~~~~~~
    at https://deno.land/x/dev_server@v1.0.0-rc4/mod.ts:144:7
```

Here is my version:
```
> deno --version
deno 1.11.5 (release, x86_64-unknown-linux-gnu)
v8 9.1.269.35
typescript 4.3.2
```

**Comment by zhmushan** [comment]
https://github.com/zhmushan/dev_server/blob/master/mod.ts#L144
In the latest Deno version we need to change `esm` to `module`, could you make a PR for this?

**Comment by NathanKleekamp** [comment]
Can someone tag a new version with this update and Deno's Third Party Modules page (if some manual action is needed for that)?
